---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

run:
  path: heka-container-src/build.sh
    
inputs:
  - name: src
  - name: heka-container-src

outputs:
  - name: out
  
