---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

inputs:
  - name: heka-src
    path: src
  - name: heka-container-src
    path: build

outputs:
  - name: heka-build
  
run:
  path: ./build/build.sh
