---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

inputs:
  - name: heka-git
    path: src
  - name: heka-container-src

outputs:
  - name: heka-build
  
run:
  path: ./heka-container-src/build.sh
