---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

run:
  path: ci/build.sh
    
inputs:
  - name: heka-container-src
    path: ci
  - name: src  
  - name: glibc

outputs:
  - name: out
  
